on:
  workflow_call:
    inputs:
        image-path:
            description: 'Path to the Docker image to be scanned'
            type: string
            required: false
            default: "/github/workspace/image.tar"
        image-tag:
          description: 'oci image tag'
          type: string
          required: false

        image-name:
          description: 'oci image name'
          type: string
          required: false
          default: 'ghcr.io/${{ github.repository }}' 
        context:
          description: 'Path to the oci context'
          type: string
          required: false
          default: "/github/workspace"
        dockerfile:
          description: 'Path to the Dockerfile'
          type: string
          required: false
          default: "/github/workspace/Dockerfile"                   




jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set IMAGE_TAG if inputs.image-tag is set
      run: |
        echo "${{ inputs.image-tag }}" > image-tag.txt
        export IMAGE_TAG=$(cat image-tag.txt)
      if: ${{ inputs.image-tag }} != ""

    - name: Set IMAGE_TAG 
      run: $GITHUB_WORKSPACE/set-image-tag.sh
      env:
        GITHUB_REF: ${{ github.ref }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_SHA: ${{ github.sha }}
      if : ${{ inputs.image-tag }} == ""  

    - name: Build Docker image with Kaniko
      # Building the Docker image using Kaniko
      id: build_image
      uses: docker://gcr.io/kaniko-project/executor:v1.23.0
      with:
        args: --destination=${{ inputs.image-name }} --context=${{ inputs.context }} --dockerfile=${{ inputs.dockerfile }} --no-push --tarPath ${{ inputs.image-path }}
    - name: Setup crane
      uses: imjasonh/setup-crane@v0.1
    - name: Use crane to get the digest
      run: crane digest --tarball=image.tar > digest.txt
    - name: Upload artifact
      # Uploading the built Docker image as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: image.tar
    - name: Upload digest
      # Uploading the built Docker image digest as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: digest
        path: digest.txt
    - name: Upload image tag
      uses: actions/upload-artifact@v4
      with:
        name: image-tag
        path: image-tag.txt      