on:
  workflow_call:
    inputs:
      asset-name:
        description: 'Name of the asset to be scanned'
        type: string
        required: true
      api-url:
        type: string
        required: false
        default: "https://api.main.devguard.org"
      sbom-artifact-name:
        description: 'Name of the SBOM artifact to be downloaded'
        type: string
        required: false
        default: ""
      sbom-file:
        description: 'Path to the SBOM file to be scanned'
        type: string
        required: true
        default: "sbom.json"
    secrets:
      devguard-token:
        description: 'DevGuard API token'
        required: true
    
jobs:
  dependency-risk-identification:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      with:
        submodules: recursive
        fetch-depth: 0
        persist-credentials: true # we need the credentials to be able to use the devguard-scanner in private repositories
      uses: actions/checkout@v4 # Check out the repository content to the runner
      
    - name: Download SBOM artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.sbom-artifact-name }}
      if: ${{ inputs.sbom-artifact-name != '' }}

    - name: DevGuard Dependency Risk Identification
      uses: docker://ghcr.io/l3montree-dev/devguard-scanner:main-latest
      with:
        args: devguard-scanner sbom ${{ inputs.sbom-file }} --assetName=${{ inputs.asset-name }}  --apiUrl=${{ inputs.api-url }} --token="${{ secrets.devguard-token }}" --defaultRef=${{ github.event.repository.default_branch }} --isTag=${{ GITHUB_REF_TYPE == 'tag' }}