on:
  workflow_call:
    inputs:
      should-deploy:
        # Input to determine if the deploy job should run
        description: 'Should the deploy job run'
        type: boolean
        required: false
        default: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ inputs.should-deploy }}
    steps:
    - name: Download oci-image artifact (can be created by build-image)
      uses: actions/download-artifact@v4
      with:
        name: oci-image
        path: .

    - name: Download image-tag artifact (can be created by build-image)
      uses: actions/download-artifact@v4
      with:
        name: image-tag
        path: .

    - name: Setup crane
      uses: imjasonh/setup-crane@v0.1

    - name: Push oci image to GitHub image Registry
      run: crane push image.tar $(cat image-tag.txt)
