# DevSecOps Workflow Definition
# This workflow is triggered on every push to the repository
name: DevGuard Workflow

on:
  push:

permissions:
  packages: write
  contents: read

jobs:
  devguard-scanner:
    uses: ./.github/workflows/full.yml
    with:
      asset-name: "l3montree-cybersecurity/projects/devguard/assets/devguard-action"
    secrets:
      devguard-token: ${{ secrets.DEVGUARD_TOKEN }}
