# DevSecOps Workflow Definition
# This workflow is triggered on every push to the repository
name: DevGuard Workflow

on:
  push:

permissions:
  packages: write
  contents: read

jobs:
  devguard-scanner:
    uses: ./.github/workflows/full.yml
    with:
      asset-name: "l3montree-cybersecurity/projects/devguard/assets/devguard-action"
      disable-artifact-registry-as-image-store: true
    secrets:
      devguard-token: ${{ secrets.DEVGUARD_TOKEN }}
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          persist-credentials: true # we need the credentials to be able to use the devguard-scanner in private repositories

      - name: print the branch name
        run: echo  git rev-parse --abbrev-ref HEAD  