on:
  workflow_call:
    inputs:
      asset-name:
        description: 'Name of the asset to be scanned'
        type: string
        required: true
      api-url:
        type: string
        required: false
        default: "https://api.main.devguard.org"
      sca-path:
        description: 'Path to the source code to be scanned'
        type: string
        required: false
        default: "."
    secrets:
      devguard-token:
        description: 'DevGuard API token'
        required: true
jobs:
  sca:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      with:
        fetch-depth: 0
        persist-credentials: false
      uses: actions/checkout@v4 # Check out the repository content to the runner
    - name: Set up Git
      run: |
        git config --global --add safe.directory /github/workspace
    - name: DevGuard SCA
      uses: docker://ghcr.io/l3montree-dev/devguard-scanner:0.7.0@sha256: 5e2083f165e20a8fde807fa9a4b81be1b0df861968e140a53bd27b74f05c6835
      with:
        args: devguard-scanner sca --assetName=${{ inputs.asset-name }}  --apiUrl=${{
          inputs.api-url }} --token="${{ secrets.devguard-token }}" --path=${{
          inputs.sca-path }}
