on:
  workflow_call:
    inputs:
      asset-name:
        description: 'Name of the asset to be scanned'
        type: string
        required: true
      api-url:
        type: string
        required: false
        default: "https://api.main.devguard.org"
      sca-path:
        description: 'Path to the source code to be scanned'
        type: string
        required: false
        default: "."
      risk-management:
        description: 'Determines if the detected risks need to be managed. This should be done for the default branch during development and for releases (tags). That is the default already'
        type: string
        required: false
        default: 'null'

    secrets:
      devguard-token:
        description: 'DevGuard API token'
        required: true
jobs:
  software-composition-analysis:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      with:
        fetch-depth: 0
      uses: actions/checkout@v4 # Check out the repository content to the runner

    - name: Determine risk-management value
      id: set-risk
      run: |
        if [[ "${{ inputs.risk-management }}" != "null" ]]; then
          # Respect the manually provided input
          echo "risk-management=${{ inputs.risk-management }}" >> $GITHUB_ENV
        else
          # Set risk-management based on branch or tag if not manually provided
          if [[ "${{ github.ref }}" == "refs/heads/${{ github.event.repository.default_branch }}" || "${{ github.ref }}" == refs/tags/* ]]; then
            echo "risk-management=true" >> $GITHUB_ENV
          else
            echo "risk-management=false" >> $GITHUB_ENV
          fi
        fi

    - name: DevGuard SCA
      uses: docker://ghcr.io/l3montree-dev/devguard-scanner@sha256:bd4a48bcd602ec6c1fcca2c7f07267f206e737b1da6654198167aaa12a4eebc7
      with:
        args: devguard-scanner sca --assetName=${{ inputs.asset-name }}  --apiUrl=${{ inputs.api-url }} --token="${{ secrets.devguard-token }}" --path=${{ inputs.sca-path }} --riskManagement=${{ env.risk-management }}
